### ISSUE TITLE
Make sure casing is canonical between sitemap and actual requests.

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/rascal-website#12]
We have quite some reports about our sitemap having urls that are then redirected to the "canonical" url, apparently google doesn't like it.

![image](https://user-images.githubusercontent.com/179603/204775130-9ded838f-4251-404c-8b9e-460278c385c0.png)

and indeed, if you check, in the sitemap.xml there is: 

```xml
<url>
<loc>https://www.rascal-mpl.org/docs/Library/Set/</loc>
<changefreq>weekly</changefreq>
<priority>0.5</priority>
</url>
```

but if you request that url you get back a result, but with a different location:

``` 
 curl -v https://www.rascal-mpl.org/docs/Library/Set/ > /dev/null
... snip
< etag: "65b63e598821e3c3446c16ab08ba816f-ssl"
< location: /docs/library/set/
< server: Netlify
< strict-transport-security: max-age=31536000
<
```

maybe this is a normalisation happening at netlify? or on our end?

**Comment by jurgenvinju** [comment]
In tutor code there is no such normalisation to lowercase and capitals are all relevant. I do capitalize every concept file name. So either it is a docusaurus thing or netlify.

**Comment by DavyLandman** [comment]
Damn, seems to be a feature of netlify: https://answers.netlify.com/t/add-ability-to-opt-out-of-enforced-lowercase/31957/7

**Comment by JJWTimmer** [comment]
is this a Netlify option? https://github.com/pester/docs/issues/36

**Comment by DavyLandman** [comment]
Nice find, I'll try and disable that

**Comment by JJWTimmer** [comment]
@DavyLandman disabled the option in Netlify and we checked the headers with curl; we think it's solved, and asked google to crawl again.
