### ISSUE TITLE
Replace old favicon by new one

### ISSUE THREAD

**Issue by PaulKlint** [usethesource/rascal-website#17]
Browser still shows the old Rascal logo (wasp) as favicon. Replace this by favicon for new logo.

**Comment by DavyLandman** [comment]
Checking here:
https://realfavicongenerator.net/favicon_checker?protocol=https&site=www.rascal-mpl.org

We can add some more favicon options.

And maybe a cachbreaker Uri?

Since what Paul is seeing is his local cache.

**Comment by JJWTimmer** [comment]
@PaulKlint I see a new logo; where do you see an old one? 

Can you try clearing the browser cache for rascal-mpl.org?

@DavyLandman cachebreaker is good idea - something like ?logo=v2 you mean, right?

**Comment by DavyLandman** [comment]
> @DavyLandman cachebreaker is good idea - something like ?logo=v2 you mean, right?

exactly. or `?cache=<hash of file>`.

**Comment by DavyLandman** [comment]
Also:

> Image https://www.rascal-mpl.org/images/favicon.png may not be useful regarding its size

Could we try and use SVG? I'm not up to date on the options for favicons, but some sharp favicon would look nice of course.
