### ISSUE TITLE
Markdown formatting mistakes

### ISSUE THREAD

**Issue by TarVK** [usethesource/rascal-website#23]
I've found a couple of mistakes in the markdown formatting (at least according to github and docusaurus' parsers). 
Apparently `|` is not allowed in a code block within a table, without escaping it.

This causes issues here: [Associativity.md?plain=1#L74](https://github.com/usethesource/rascal-website/blob/website-v2/courses/Rascal/Declarations/SyntaxDefinition/Disambiguation/Associativity/Associativity.md?plain=1#L74)
Which can be fixed by writing the following instead:
```
| `E = left ( "+" E \| E "+" E );` | `E = E "+" E > "+" E;`  |
| `E = right ( "+" E \| E "+" E );` | `E = "+" E > E "+" E;`  |
| `E = left ( E "+" \| E "+" E);` | `E = E "+" > E "+" E;`  |
| `E = right ( E "+" \| E "+" E);` | `E = E "+" E > E "+" ;` |
```

The same applies here: [Regular.md?plain=1#L98](https://github.com/usethesource/rascal-website/blob/website-v2/courses/Rascal/Patterns/Regular/Regular.md?plain=1#L98)

There may be another couple of pages, like this, but these are the ones I encountered. 

I am not a 100% sure if this properly fixes the issue though. It does fix it in github, but it seems docusaurus may not be getting rid of the escapement `\` properly, given that at the very bottom of the operators page the `\` is still present: https://www.rascal-mpl.org/docs/Rascal/Expressions/Operators/ .

**Comment by TarVK** [comment]
I only just noticed that the other tables on this associativity page are also not rendering properly.

This is likely due to this vertical bar: [Associativity.md?plain=1#LL41C20-L41C21](https://github.com/usethesource/rascal-website/blob/website-v2/courses/Rascal/Declarations/SyntaxDefinition/Disambiguation/Associativity/Associativity.md?plain=1#LL41C20-L41C21)
Combined with there being 6 instead of 5 dividers here: [Associativity.md?plain=1#LL42C1-L42C38](https://github.com/usethesource/rascal-website/blob/website-v2/courses/Rascal/Declarations/SyntaxDefinition/Disambiguation/Associativity/Associativity.md?plain=1#LL42C1-L42C38)

This is however the case for both of these tables, so I do not know what would cause one to not render as a table at all, while the other is just rendered a bit improperly. Maybe a blank line is also required above tables.

**Comment by jurgenvinju** [comment]
Thanks @TarVK ; fixed all of the above. If we run into more, we'll know what to do. My `grep` produced too many false positives.
