### ISSUE TITLE
Fix anchors 

### ISSUE THREAD

**Issue by JJWTimmer** [usethesource/rascal-website#25]
There are some anchor tags not being processed properly. I think we need to normalize or remove the special characters.

![Screenshot_2023-07-12-18-27-06-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/usethesource/rascal-website/assets/609540/eb182bd5-8f49-47b9-b1ef-54957f9e5809)

**Comment by jurgenvinju** [comment]
Check. The type parameters of data-types do not add to the uniqueness of their name, so we can simply remove them from the anchor.
