### ISSUE TITLE
Website improvement suggestions

### ISSUE THREAD

**Issue by JJWTimmer** [usethesource/rascal-website#3]
1. Put a link to the reference library on the homepage
2. Use terminology people are used to. When I encounter a new proglang, I want to dive in the docs fast. With Rascal I have to click 'help' (which for me means: contact somebody) and then 'tutor' (which means nothing to me, I'm looking for docs). And in Tutor I have to click 'Rascal: Language and libraries' instead of 'reference documentation'. As a new developer, you would have lost me.
3. Don't open links in new windows (I can decide myself if I want to open in a new tab/window nowadays)
4. Put the version number for which rascal version the docs are, in the footer of the docs

**Comment by PaulKlint** [comment]
Hi Jasper, these are all valid comments. We are working on a better organization of our documentation but that is not yet accessible via the website and we will give serious consideration to your suggestions.

Thanks for your feedback!

**Comment by jurgenvinju** [comment]
I'm leaving this one open; still valid concerns.

**Comment by JJWTimmer** [comment]
Almost a year after date, and we are live with a new website, whoho!
1. More clear now although reference docs are still a few clicks away. TODO: restructure documentation.
2. Tutor is now Docs, the feature to create docs is still called Tutor though. For me it's good enough.
3. Fixed
4. For now always latest docs = latest rascal version

**Comment by JJWTimmer** [comment]
1. Packages are more clear, Std. lib needs an icon and we are slowly reshuffling the docs.
2. already good
3. already good
4. API docs have a version now!

I'm closing the issue!

**Comment by jurgenvinju** [comment]
Wow! Progress 🎉 thanks Jasper
