### ISSUE TITLE
Many screencaptures not 'finished'

### ISSUE THREAD

**Issue by JJWTimmer** [usethesource/rascal-website#33]
As reported by @jurgenvinju, many screenshots are not created OK, eg. on https://www.rascal-mpl.org/docs/Library/vis/Charts/ there are white squares.

Locally everything working according to @jurgenvinju. It's only on the GitHub Actions runners going wrong.

Probably selenium not waiting long enough (page ready?).

I don't know where to look for this issue, but I want to report it here so others can see it's a known issue.

**Comment by jurgenvinju** [comment]
I think it has to be solved in usethesource/rascal-tutor where we use selenium to take the screenshots. I'm contemplating adding loop that keeps taking shots until the last two are equal. The current code is already waiting for the document ready state and the rendering of the body element. The problem resides in css animations and js code channging positions on canvases, etc. There is no generic API to wait for that. On slow machines or busy machines this means we take the shot too early.

**Comment by jurgenvinju** [comment]
Fixed by commit 9c38432c31bbc6d35e3cd137f28737b66fb9d543 and the corresponding fix in usethesource/rascal-tutor and the release of usethesource/rascal-maven-plugin
