### ISSUE TITLE
apply the new Rascal logo

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-website#6]
Any CSS heroes ready to answer this call for help?

**Comment by jurgenvinju** [comment]
![rascal_logo](https://user-images.githubusercontent.com/1990295/146923914-2be317c1-420a-4e7c-96ba-68c5086e4902.png)
![rascal_beeldmerk](https://user-images.githubusercontent.com/1990295/146923941-8ddea752-cf50-420a-9f82-454401067296.png)
![rascal_line_gradient](https://user-images.githubusercontent.com/1990295/146923959-59ef1b4d-218e-4b7e-aead-1513675a6f02.png)



![rascal_logo_16px](https://user-images.githubusercontent.com/1990295/146923987-ff256250-f6b7-4ba7-8849-e5bca12d9da4.png)
![rascal_logo_32px](https://user-images.githubusercontent.com/1990295/146923989-23dc72a7-8422-47b8-b0fc-bc5a8b6400ea.png)
![rascal_logo_64px](https://user-images.githubusercontent.com/1990295/146923990-824b7278-03d8-4762-84cf-8127478863cb.png)

**Comment by JJWTimmer** [comment]
@jurgenvinju done, right? :)

**Comment by DavyLandman** [comment]
more than done 🎉
